yarnPath: .yarn/releases/yarn-3.8.0.cjs

packageExtensions:
  '@toast-ui/editor@*':
    dependencies:
      prosemirror-transform: '*'

  '@toast-ui/react-editor@*':
    dependencies:
      prosemirror-transform: '*'